name: Update Gas Prices

on:
  schedule:
    - cron: "0 10 * * *"  # runs daily at ~6 AM ET
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - run: pip install requests beautifulsoup4 gspread google-auth

      - name: Write creds file
        run: echo "$GOOGLE_CREDS" > creds.json
        env:
  GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
  SHEET_ID: ${{ vars.SHEET_ID }}

      - name: Run script
        run: python update_gas.py
